export const CHECK_IN_HABIT = 'CHECK_IN_HABIT';
export const ADD_OR_EDIT_HABIT = 'ADD_OR_EDIT_HABIT';
export const SAVED_DATA = 'SAVED_DATA';
export const SAVE_FAILED = 'SAVE_FAILED';
export const ADD_HABIT_PACK = 'ADD_HABIT_PACK';
export const UPDATE_AVAILABLE_HABIT_PACKS = 'UPDATE_AVAILABLE_HABIT_PACKS';
